"""add_subscription_fields_to_users

Revision ID: 81dac28033b4
Revises: f37c00259973
Create Date: 2026-02-26 19:58:08.797450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dac28033b4'
down_revision: Union[str, None] = 'f37c00259973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_ends_at')
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###
