"""Add featured_videos to users

Revision ID: 909a58992ff0
Revises: b1c2d3e4f5a6
Create Date: 2026-03-21 16:39:23.293046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '909a58992ff0'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    if not is_sqlite:
        op.drop_constraint('users_agency_id_fkey', 'users', type_='foreignkey')
        op.drop_constraint('agency_members_agency_id_fkey', 'agency_members', type_='foreignkey')
        op.drop_constraint('agency_members_user_id_fkey', 'agency_members', type_='foreignkey')
        op.drop_constraint('agency_transfer_codes_client_id_fkey', 'agency_transfer_codes', type_='foreignkey')
        op.drop_constraint('agency_transfer_codes_from_agency_id_fkey', 'agency_transfer_codes', type_='foreignkey')

    # Now drop the tables
    try:
        op.drop_table('agency_members')
    except Exception:
        pass
    
    # We must try-except dropping indices in SQLite if they don't exist
    try:
        op.drop_index('ix_agency_transfer_codes_code', table_name='agency_transfer_codes')
        op.drop_index('ix_agency_transfer_codes_id', table_name='agency_transfer_codes')
    except Exception:
        pass
    try:
        op.drop_table('agency_transfer_codes')
    except Exception:
        pass
    
    try:
        op.drop_index('ix_agencies_id', table_name='agencies')
        op.drop_index('ix_agencies_slug', table_name='agencies')
    except Exception:
        pass
    try:
        op.drop_table('agencies')
    except Exception:
        pass

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('featured_videos', sa.JSON(), nullable=True))
        batch_op.drop_column('agency_id')
        batch_op.drop_column('agency_details')
        batch_op.drop_column('agency_onboarded')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agency_onboarded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('agency_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('agency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_agency_id_fkey', 'users', 'agencies', ['agency_id'], ['id'])
    op.drop_column('users', 'featured_videos')
    op.create_table('agency_members',
    sa.Column('agency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name='agency_members_agency_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='agency_members_user_id_fkey'),
    sa.PrimaryKeyConstraint('agency_id', 'user_id', name='agency_members_pkey')
    )
    op.create_table('agency_transfer_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('from_agency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='agency_transfer_codes_client_id_fkey'),
    sa.ForeignKeyConstraint(['from_agency_id'], ['agencies.id'], name='agency_transfer_codes_from_agency_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agency_transfer_codes_pkey')
    )
    op.create_index('ix_agency_transfer_codes_id', 'agency_transfer_codes', ['id'], unique=False)
    op.create_index('ix_agency_transfer_codes_code', 'agency_transfer_codes', ['code'], unique=True)
    op.create_table('agencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='agencies_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agencies_pkey')
    )
    op.create_index('ix_agencies_slug', 'agencies', ['slug'], unique=True)
    op.create_index('ix_agencies_id', 'agencies', ['id'], unique=False)
    # ### end Alembic commands ###
